// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4v7bdQAnviFKh8QyKE8VKgcGXg-6u_9w',
    appId: '1:445464943064:web:079f0bcccdaa3a8a2c7aad',
    messagingSenderId: '445464943064',
    projectId: 'bigu-huini',
    authDomain: 'bigu-huini.firebaseapp.com',
    storageBucket: 'bigu-huini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wsTyYbbtmmZLZ8JMM9kz_ih4vVmqULE',
    appId: '1:445464943064:android:d0e46c8f1abb083b2c7aad',
    messagingSenderId: '445464943064',
    projectId: 'bigu-huini',
    storageBucket: 'bigu-huini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39OT7auZIvBXzA0GDbygrjjQkQGcUM0c',
    appId: '1:445464943064:ios:48ca87b65489b9022c7aad',
    messagingSenderId: '445464943064',
    projectId: 'bigu-huini',
    storageBucket: 'bigu-huini.appspot.com',
    iosClientId: '445464943064-pqbk9mie70jq1r55s4kl2ketepr328rt.apps.googleusercontent.com',
    iosBundleId: 'app.learn.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39OT7auZIvBXzA0GDbygrjjQkQGcUM0c',
    appId: '1:445464943064:ios:48ca87b65489b9022c7aad',
    messagingSenderId: '445464943064',
    projectId: 'bigu-huini',
    storageBucket: 'bigu-huini.appspot.com',
    iosClientId: '445464943064-pqbk9mie70jq1r55s4kl2ketepr328rt.apps.googleusercontent.com',
    iosBundleId: 'app.learn.firstApp',
  );
}
